### PR TITLE
add simple route and data for glider data

### PR DESCRIPTION
**Pull request by birdage**
@DanielJMaher @benjwadams @oceanzus this is the services end work for the glider tracks, @benjwadams take this and commit to it, most of the work is done just change the glider function, remove static dict and add reference designator and request to uframe.

DO NOT MERGE (until @benjwadams makes changes)

### CODE REVIEW

**Comment by benjwadams** [comment]
I still have this in the controller code etc., but I don't really see the point of introducing this in the commit history.  I'll create a new PR and reference this one as a parent.

**Comment by benjwadams** [comment]
Update, WIP here:  https://github.com/benjwadams/ooi-ui-services/commit/8f700d46d862d0e962bd59c0e529057152b9ab9b

Fetches GeoJSON properly on 200 status but needs to handle error cases i.e. 404, 50x series.  I had trouble testing this because I could not figure out how to pass auth credentials to `manage.py shell`

**Comment by DanielJMaher** [comment]
@birdage @benjwadams SO we are not committing this guy?  Waiting on Ben's?

**Comment by birdage** [comment]
@DanielJMaher, @benjwadams is going to make some changes so we can test

**Comment by birdage** [comment]
closed in favor of #269

**Pull request closed without merging**
