### PR TITLE
Adds display name

### PR DESCRIPTION
**Pull request by oceanzus**

### CODE REVIEW

**Comment by oceanzus** [comment]
@lukecampbell @FBRTMaka 
Good to merge?

**Comment by lukecampbell** [comment]
Is platform name defined in the models?

**Comment by oceanzus** [comment]
Yes, as Platformname (table).  It is also in the sql scripts.  In the platforms table there is a platform_name' field.  Not sure which one you are referring to.

**Comment by FBRTMaka** [comment]
this looks a lot like model logic mixed in with the route, maybe double check that it should/should not be in the class def of it's respective names?

**Pull request merged**
