### PR TITLE
added download link for netcdf3 files

### PR DESCRIPTION
**Pull request by DanielJMaher**
@lukecampbell @FBRTMaka @birdage 

MERGE THIS

### CODE REVIEW

**Comment by birdage** [comment]
@DanielJMaher why netcdf3?

**Comment by birdage** [comment]
is this a uframe thing?

**Comment by DanielJMaher** [comment]
Yea uFrame has to use netcdf3 for now.  They are switching their internals to allow netcdf4, but for now we only get 3

**Comment by DanielJMaher** [comment]
Made an error.  fixing it.  WIll re-pull in a few

**Pull request closed without merging**
