### PR TITLE
/uframe/events/<string:ref_des> 

### PR DESCRIPTION
**Pull request by FBRTMaka**
@Bobfrat , @DanielJMaher 

This route will return the following format if used as follows (example):

```
http://localhost:4000/uframe/events/CP05MOAS-GL004-01-ADCPAM000
HTTP/1.0 200 OK
Access-Control-Allow-Origin: *
Content-Length: 660
Content-Type: application/json
Date: Wed, 29 Apr 2015 18:19:29 GMT
Server: Werkzeug/0.9.6 Python/2.7.9
Set-Cookie: session=***
```
```
{
    "events": [
        {
            "class": ".DeploymentEvent", 
            "event_description": null, 
            "event_type": "ACTUAL", 
            "notes": [], 
            "ref_des": "CP05MOAS-GL004-01-ADCPAM000", 
            "start_date": 1412643960000, 
            "uframe_url": "http://uframe-test.ooi.rutgers.edu:12573/events/32", 
            "url": "/uframe/events/32"
        }
    ]
}

### CODE REVIEW

**Comment by FBRTMaka** [comment]
Note: The cache is prepped, but not implemented yet for continued dev.

**Comment by DanielJMaher** [comment]
It is going to return all of the events for that ref_des? @FBRTMaka

**Comment by FBRTMaka** [comment]
yup!

**Comment by DanielJMaher** [comment]
Looks good to me

**Comment by FBRTMaka** [comment]
Hang on, trying to find a ref des with more than one event

**Comment by FBRTMaka** [comment]
haha, no it won't @DanielJMaher ... but it will in a few min!

**Comment by FBRTMaka** [comment]
@DanielJMaher , @Bobfrat 

Ok, good to go!

**Comment by DanielJMaher** [comment]
@FBRTMaka Take your time.  Make sure it is right.  Worst thing would be Bob working it and it having a hiccup hidden in it.

When you think you are good to go, post the output so we can verify.

**Comment by FBRTMaka** [comment]
@DanielJMaher , I haven't been able to find a logical instrument that has more than one event associated with it. I'll mock up a test json to make sure it works.  Everything looks just about ready though.

**Pull request merged**
