### PR TITLE
update data services

### PR DESCRIPTION
**Pull request by birdage**
DO NOT MERGE YET, related to a UI PR coming soon

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@birdage Update when the UI part is ready?

**Comment by birdage** [comment]
@DanielJMaher i wanted to get the pull request open for the changes i made to the services @FBRTMaka @oceanzus take a took at what i have so far, shouldn't affect either of you. Allows the UI to take better to the services for data access!

**Comment by birdage** [comment]
@DanielJMaher @Bobfrat this goes with the highcharts integration and needs to be merged as well

**Comment by DanielJMaher** [comment]
@Bobfrat Before you make that other merge for high charts, coordinate with Andy on this bad boy

**Comment by Bobfrat** [comment]
:+1:

**Pull request merged**
