### PR TITLE
Adds code coverage.

### PR DESCRIPTION
**Pull request by oceanzus**

### CODE REVIEW

**Comment by oceanzus** [comment]
Adding something, do not merge yet

**Comment by Bobfrat** [comment]
:+1:  Thanks for adding coverage to the redmine tests

**Comment by oceanzus** [comment]
Edna deserves all the credit, but was scared of this git merge, so I get all the credit...and the blame!!

**Comment by oceanzus** [comment]
@lukecampbell @FBRTMaka please review and merge if okay with you

**Comment by FBRTMaka** [comment]
reviewing!

**Comment by FBRTMaka** [comment]
damn. good. stuff. :+1:

**Pull request merged**
