### PR TITLE
Adds SystemEventDefinition and SystemEvent tables for alerts and alarms.

### PR DESCRIPTION
**Pull request by oceanzus**

### CODE REVIEW

**Comment by oceanzus** [comment]
@brian-smith723 @FBRTMaka  Please review to see if this works for your alerts and alarms definition and response storage requirements.

**Comment by brian-smith723** [comment]
Everything looks good. I don't know if we are assigning alarms by user or organization? At the moment I have it set up to assign alarms to redmine users...The only variable I have that is not included is notification. Users can select among 5 different notifications: text message, phone call, email, redmine, log event. But, then again I don't know if we are going use notifications...

**Comment by oceanzus** [comment]
I'll add the notification type and update this branch/PR

**Comment by oceanzus** [comment]
@DanielJMaher @brian-smith723 @FBRTMaka Are we good to go with this one?

**Comment by DanielJMaher** [comment]
@oceanzus I like it.  If @FBRTMaka doesn't respond in 30 minutes I will merge.

**Pull request merged**
