### PR TITLE
Enables a platform list reponse from uframe.

### PR DESCRIPTION
**Pull request by FBRTMaka**
@DanielJMaher , @bnfish , @brian-smith723 

This asset will be our bread and butter, it's pretty much got full asset to stream support (it's in our uframe asset list AND in what rutgers has online):

```
"CP02PMCI": {
    "assetId": 525, 
    "assetInfo": {
      "description": null, 
      "name": null, 
      "owner": null, 
      "type": "WiFi"
    }, 
    "coordinates": [
      null, 
      null
    ], 
    "url": "/uframe/assets/525"
  }
```

### CODE REVIEW

**Comment by FBRTMaka** [comment]
@bnfish , @brian-smith723 :
This is the asset record (we have) for what rutgers has at this url:

http://uframe-test.ooi.rutgers.edu:12575/sensor/inv/CP02PMCI

```
{
  "assetId": 525, 
  "assetInfo": {
    "description": null, 
    "name": null, 
    "owner": null, 
    "type": "WiFi"
  }, 
  "attachments": [], 
  "class": ".AssetRecord", 
  "events": [], 
  "manufactureInfo": {
    "manufacturer": null, 
    "modelNumber": "1319G", 
    "serialNumber": "WIFI SN 012"
  }, 
  "metaData": [
    {
      "key": "Platform", 
      "metaId": 6049, 
      "type": "java.lang.String", 
      "value": "CP02PMCI"
    }, 
    {
      "key": "MAC Address", 
      "metaId": 6048, 
      "type": "java.lang.String", 
      "value": "DC9FDB6A0086"
    }
  ], 
  "notes": [], 
  "physicalInfo": null, 
  "purchaseAndDeliveryInfo": null
}
```

**Comment by FBRTMaka** [comment]
@birdage , we can do a PUT on this asset to give it real coordinates if you want.

**Comment by birdage** [comment]
@FBRTMaka ben is working on a shortcut (that we talked about) at the min to get the asset locations in place. basically overriding the platform deployments with the uframe platform locations.

**Comment by DanielJMaher** [comment]
@birdage @FBRTMaka Someone give me status here?

**Comment by FBRTMaka** [comment]
@DanielJMaher Just making sure the structure of this is logically sound, almost done.

**Comment by DanielJMaher** [comment]
@FBRTMaka @birdage soooooo?

**Comment by FBRTMaka** [comment]
New way of doing this inbound...stay tuned.

**Pull request closed without merging**
