### PR TITLE
new vocab updates

### PR DESCRIPTION
**Pull request by FBRTMaka**
@oceanzus , @birdage , @Bobfrat , @ednad , @DanielJMaher 

Hey all, I made some significant changes to how the asset names are interpreted based on the reference designators.

@oceanzus , @ednad  I created a separate sql file that will load to a new table via the manage.py file.  I'm not married to this implementation, so if you need/want to make any changes let me know and I can update that.

@Bobfrat , @birdage, at this point it's really a consistency check and an exercise of rebuilding the DB with this new data.  We should get together today if possible to work out what need to do to keep the UI happy.

@birdage , lets look in detail at line 115 of routes.py and if we need to keep that or off load that hack to be on uframes plate instead.

Let me know if you need a hand setting it back up!

### CODE REVIEW

**Comment by birdage** [comment]
@FBRTMaka looks good. how do we plan to handle `geo_locations` since that route was removed? (not sure where that was used from?)

**Comment by oceanzus** [comment]
@FBRTMaka I think the separate vocab sql file approach is fine.  How was that file produced?  It needs to be insert statements and set up like the other 2 sql files.

**Comment by FBRTMaka** [comment]
@birdage Good question, I may be missing the mark but I did a search of the routes directory in UI's flask proxy and didn't find any reference to /platformlocation being used.

**Comment by FBRTMaka** [comment]
It was created with pg_dump.  What do you use to export the sql file with insert statements instead of COPY ?


On Dec 22, 2015, at 10:39 AM, James Case <notifications@github.com<mailto:notifications@github.com>> wrote:


@FBRTMaka<https://github.com/FBRTMaka> I think the separate vocab sql file approach is fine. How was that file produced? It needs to be insert statements and set up like the other 2 sql files.

—
Reply to this email directly or view it on GitHub<https://github.com/asascience-open/ooi-ui-services/pull/465#issuecomment-166650020>.


This e-mail message and any attached file is the property of the sender and is sent in confidence to the addressee only.
Internet communications are not secure and RPS is not responsible for their abuse by third parties, any alteration or corruption in transmission or for any loss or damage caused by a virus or by other means.
 
Any advice contained in this e-mail is for information purposes only.

RPS Group Plc, company number: 208 7786 (England). Registered office: 20 Western Avenue Milton Park Abingdon Oxfordshire OX14 4SH.
RPS Group Plc web link: <http://www.rpsgroup.com>

**Comment by oceanzus** [comment]
use the --column-inserts option in the pg_dump
Also, hand edit the top of the sql file to look like the others and make sure you really need that sequence statement in there.

**Comment by DanielJMaher** [comment]
@birdage @FBRTMaka interesting new thing in uframe... every stream has an associated lat/lon... i dont think that is how we want to be using it, but more than likely those fields are being populated by uframe from the asset management sheet.  That means that their will be a push to get every asset record to have a lat/lon.  We have to develop a solution for now, but i think long term that wil be the path

**Comment by oceanzus** [comment]
@FBRTMaka 
Not sure this should be set to 1 if the data goes to 1235
SELECT pg_catalog.setval('vocabnames_id_seq', 1, false);

**Pull request merged**
