### PR TITLE
Cruise docs

### PR DESCRIPTION
**Pull request by birdage**
@DanielJMaher @FBRTMaka REQUIRES CONFIG UPDATE!!!

### CODE REVIEW

**Comment by FBRTMaka** [comment]
@birdage looks great! :+1:

**Comment by DanielJMaher** [comment]
I thought we were waiting on these until we had instrument examples... @FBRTMaka @birdage

**Comment by FBRTMaka** [comment]
@DanielJMaher we were not

**Comment by DanielJMaher** [comment]
@FBRTMaka lol apparently not.  It is okay because they want to change how they do the assets anyway per our discussions.  They haven't even fully ingested that thought yet.

**Comment by FBRTMaka** [comment]
@DanielJMaher it IS ok! :D

**Pull request merged**
