### PR TITLE
improved searching for logical 'and' results

### PR DESCRIPTION
**Pull request by FBRTMaka**
@DanielJMaher , @oceanzus , Please review the search method for streams and assets

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@birdage

**Comment by birdage** [comment]
@DanielJMaher @FBRTMaka @oceanzus this looks good to me, merge when ready. requires testing

**Comment by FBRTMaka** [comment]
@birdage just merged in Jim's stuff - when test is done it's ready to go!

**Comment by DanielJMaher** [comment]
@oceanzus This looks good to me, but I want a second opinion

**Pull request merged**
