### PR TITLE
Improves Data Catalog Population Speed

### PR DESCRIPTION
**Pull request by DanielJMaher**

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@birdage

**Comment by DanielJMaher** [comment]
@oceanzus

**Comment by DanielJMaher** [comment]
I removed some function we no longer use as well.

**Comment by oceanzus** [comment]
Looks about right.  Has any regression testing been done given how much controller.py is used by other methods?

**Comment by DanielJMaher** [comment]
No formal testing.. i just searched if the functions were referenced in our code base.. i didnt find anything

**Comment by FBRTMaka** [comment]
Tests? Were we're going we don't need..tests.

**Comment by DanielJMaher** [comment]
@oceanzus Are we going to merge or not yet? would love this for my demo today

**Pull request merged**
