### PR TITLE
add metadata uframe connection

### PR DESCRIPTION
**Pull request by birdage**
add metadata routes

### CODE REVIEW

**Comment by birdage** [comment]
@DanielJMaher @oceanzus can i get this merged asap pls

**Comment by birdage** [comment]
@brian-smith723 for info

**Comment by oceanzus** [comment]
As soon as it passes and the print is removed :)

**Comment by DanielJMaher** [comment]
k

**Comment by birdage** [comment]
@DanielJMaher it passed

**Pull request merged**
