### PR TITLE
update the services to allow for a field to be returned

### PR DESCRIPTION
**Pull request by birdage**
@lukecampbell @FBRTMaka adds field to the request so we dont return all the data to the ui

### CODE REVIEW

**Comment by birdage** [comment]
@lukecampbell dont merge yet i wanna add time averaging to this one etc

**Comment by FBRTMaka** [comment]
You’ve also got conflicts!


On Feb 9, 2015, at 1:32 PM, Andrew Bird <notifications@github.com<mailto:notifications@github.com>> wrote:


@lukecampbell<https://github.com/lukecampbell> dont merge yet i wanna add time averaging to this one etc

**Comment by FBRTMaka** [comment]
nm, you fixed it!

On Feb 9, 2015, at 1:32 PM, Andrew Bird <notifications@github.com<mailto:notifications@github.com>> wrote:


@lukecampbell<https://github.com/lukecampbell> dont merge yet i wanna add time averaging to this one etc

**Comment by birdage** [comment]
@FBRTMaka get yo facts straight son!

**Comment by birdage** [comment]
@lukecampbell @FBRTMaka ready for merge

**Comment by FBRTMaka** [comment]
:+1:

**Pull request merged**
