### PR TITLE
Mc permissions

### PR DESCRIPTION
**Pull request by FBRTMaka**
need the u'

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@oceanzus The 'u' matters?  odd

**Comment by oceanzus** [comment]
@DanielJMaher I didn't write the scope_required or .can method, but I suppose sqlalchemy likes the unicode variant in the .can method under Users in models.py

**Comment by DanielJMaher** [comment]
@oceanzus @FBRTMaka I'm going to merge unless someone can tell me why i shouldnt.

**Comment by oceanzus** [comment]
@DanielJMaher go ahead and merge it

**Pull request merged**
