### PR TITLE
User Registration - Red MineIntegration

### PR DESCRIPTION
**Pull request by ssontag55**
You'll need to create and update the config.yaml: REDMINE_KEY/SECRET_KEY and UI_API_KEY

### CODE REVIEW

**Comment by FBRTMaka** [comment]
hey @ssontag55 , this should live in the redmine user route, not in the ooi user route.  Then pull the needed info from the db (role, org, etc).

**Comment by DanielJMaher** [comment]
@ssontag55 Need to add back in the netcdf dependency.

**Comment by DanielJMaher** [comment]
@FBRTMaka Why does he need to move this?

**Comment by lukecampbell** [comment]
My intent with this, as prescribed by the requirements, is that when a new user account is created a redmine issue is generated that tells <someone> to enable his/her account.

**Comment by FBRTMaka** [comment]
That makes sense, so then you call the url_for(create_redmine_ticket) and supply the new user info

**Comment by FBRTMaka** [comment]
@ssontag55 , you should rework this code from the approach that we have a route for creating a ticket already.  Let the redmine/route handle the lifting and config.

**Comment by ssontag55** [comment]
I did that at first, but why have another level request when you can just
have 4 lines of code and call it in the same function?



Stephen

**Comment by DanielJMaher** [comment]
@FBRTMaka @ssontag55 We can discuss where this sits another time.  Let's keep it where it is for now, and add it as a Bug in delviery 4.  We don't have time to rewrite the code, and I'm not overly sold that it is in the wrong place.  

Let's get the Travis CI test fixed so it properly creates the user and see if Travis CI builds.  Once we resolve all TravisCI failures, we will merge the code.

**Comment by FBRTMaka** [comment]
Well, it's not really a matter of being in the wrong place but more so it's duplicating what we already have.  If it's written efficiently then the travis ci issue will go away.  But, just saying.  You're the boss!

**Comment by DanielJMaher** [comment]
No, the Travis CI test isn't creating a user properly (No First or Last Name, both required fields).  That's my concern.  

If this could all be reworked by COB tomorrow and we could get everything else done, I would be all for reworking the code, but I don't see that as an option.

**Comment by FBRTMaka** [comment]
If this is trying to create a user, why is in the GET method and not the POST?

**Comment by FBRTMaka** [comment]
ignore that last bit

**Comment by DanielJMaher** [comment]
@FBRTMaka No worries, I always ignore you!

**Comment by ssontag55** [comment]
This needs REDMINE_KEY/SECRET_KEY and UI_API_KEY to create an issue, that is why it failed.  Should I push the key?

**Comment by oceanzus** [comment]
That doesn't sound like a good idea.

**Comment by FBRTMaka** [comment]
Which, is why it should use the route from the redmine blueprint...it has this all figured out already...

**Comment by DanielJMaher** [comment]
Do not push the key @ssontag55

**Comment by DanielJMaher** [comment]
@ssontag55 

We have an error and a fail.  We need to get this hammered out tomorrow.  Error is a little weird to me, maybe i have an old version of the test.  failure is based off your recent changes.  I think the test is wrong though, not your code.

**Pull request merged**
