### PR TITLE
glider gps lat/lon issue

### PR DESCRIPTION
**Pull request by birdage**
@FBRTMaka @DanielJMaher i had an issue with gps position not being in the streaming causing the glider load to fail. this is a short term fix in case you need it...
``` python
  File ".../uframe/controller.py", line 143, in data_streams_in_instrument
    parameters_dict[data_stream['stream']],
KeyError: u'glider_gps_position'
```

### CODE REVIEW

**Comment by Bobfrat** [comment]
@DanielJMaher @birdage  I'm getting this error too. So this PR just skips the glider gps streams for now?

**Comment by FBRTMaka** [comment]
@birdage @DanielJMaher @Bobfrat ,  It'll omit that one record, possibly to take it one step further and ensure this doesn't happen again would be to replace the IF with a try/except block that handles KeyErrors.  We'd still want to see other errors if they pop up, but handling this exception nicely would be a bonus (rather than ignoring it with a IF).

**Comment by birdage** [comment]
@FBRTMaka @Bobfrat was a quick fix for those who are getting the issue, i agree a more permanent solution would be preferable!

**Comment by FBRTMaka** [comment]
@birdage great! I'm actually not using this (I implemented the try/except) so I can make a PR for that and close this one if no objection.

**Comment by birdage** [comment]
@FBRTMaka sounds good!

**Comment by FBRTMaka** [comment]
@birdage you got it!  @DanielJMaher PR coming in with a perma solution that'll provide error handling.

**Pull request closed without merging**
