### PR TITLE
adds parameter to name mapping in sql db, new param name def and impl…

### PR DESCRIPTION
**Pull request by RyanMaciel**
…emented in streams endpoint
@FBRTMaka

### CODE REVIEW

**Comment by FBRTMaka** [comment]
:+1: Nice job Ryan!!

**Comment by oceanzus** [comment]
This change breaks deployment on both Linux and Windows and at a minimum breaks C2.  Why in the world was so much of this file changed?

**Comment by FBRTMaka** [comment]
@oceanzus what are the errors?

**Comment by oceanzus** [comment]
python ooiservices/manage.py rebuild_schema --schema ooiui --schema_owner postgres --save_users False

yields

  File "C:\Users\James\Documents\GitHub\ooi-ui-services\ooiservices\app\models.py", line 1190, in insert_user
    user.organization_id = org.id
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by FBRTMaka** [comment]
Did you try:

python ooiservices/manage.py deploy -p <password> -bl=True   ?

Not sure what those args are, is that for the OS difference?

—
Matt


On Oct 22, 2015, at 1:35 PM, James Case <notifications@github.com<mailto:notifications@github.com>> wrote:


python ooiservices/manage.py rebuild_schema --schema ooiui --schema_owner postgres --save_users False

yields

File "C:\Users\James\Documents\GitHub\ooi-ui-services\ooiservices\app\models.py", line 1190, in insert_user
user.organization_id = org.id
AttributeError: 'NoneType' object has no attribute 'id'

—
Reply to this email directly or view it on GitHub<https://github.com/asascience-open/ooi-ui-services/pull/419#issuecomment-150299850>.


This e-mail message and any attached file is the property of the sender and is sent in confidence to the addressee only.
Internet communications are not secure and RPS is not responsible for their abuse by third parties, any alteration or corruption in transmission or for any loss or damage caused by a virus or by other means.
 
Any advice contained in this e-mail is for information purposes only.

RPS Group Plc, company number: 208 7786 (England). Registered office: 20 Western Avenue Milton Park Abingdon Oxfordshire OX14 4SH.
RPS Group Plc web link: <http://www.rpsgroup.com>

**Comment by oceanzus** [comment]
Not on a Windows machine.  This worked fine before the changes on all platforms and now it is broken on all platforms.  What was the purpose of these changes and why the heavy hand on the file?

**Comment by FBRTMaka** [comment]
Strange. . .

this was just a dump of the updated database, not heavy handed just standard export w/o the schema.  It’s basically just insert statements, so it should work no matter how you load it (you could try load this file directly to the db).

It’d def not broken on all platforms, as I was able to load this in with no trouble.  You should try the params I suggested, it was the original and should be default — unless it absolutely doesn’t work for Windows / Linux.

I’ll get my own linux / windows instances running to see as well.

—
Matt

On Oct 22, 2015, at 1:51 PM, James Case <notifications@github.com<mailto:notifications@github.com>> wrote:


Not on a Windows machine. This worked fine before the changes on all platforms and now it is broken on all platforms. What was the purpose of these changes and why the heavy hand on the file?

—
Reply to this email directly or view it on GitHub<https://github.com/asascience-open/ooi-ui-services/pull/419#issuecomment-150304729>.


This e-mail message and any attached file is the property of the sender and is sent in confidence to the addressee only.
Internet communications are not secure and RPS is not responsible for their abuse by third parties, any alteration or corruption in transmission or for any loss or damage caused by a virus or by other means.
 
Any advice contained in this e-mail is for information purposes only.

RPS Group Plc, company number: 208 7786 (England). Registered office: 20 Western Avenue Milton Park Abingdon Oxfordshire OX14 4SH.
RPS Group Plc web link: <http://www.rpsgroup.com>

**Comment by oceanzus** [comment]
This only works if you DROP the entire database each time the schema needs to be refreshed because of the sequence method introduced in the PR.

**Comment by FBRTMaka** [comment]
Ok, so what parameters do you use when you export the DB?  I can redo the export with those parameters and make a new PR so that it can work with this custom migration method.

—
Matt

On Oct 22, 2015, at 2:18 PM, James Case <notifications@github.com<mailto:notifications@github.com>> wrote:


This only works if you DROP the entire database each time the schema needs to be refreshed because of the sequence method introduced in the PR.

—
Reply to this email directly or view it on GitHub<https://github.com/asascience-open/ooi-ui-services/pull/419#issuecomment-150311341>.


This e-mail message and any attached file is the property of the sender and is sent in confidence to the addressee only.
Internet communications are not secure and RPS is not responsible for their abuse by third parties, any alteration or corruption in transmission or for any loss or damage caused by a virus or by other means.
 
Any advice contained in this e-mail is for information purposes only.

RPS Group Plc, company number: 208 7786 (England). Registered office: 20 Western Avenue Milton Park Abingdon Oxfordshire OX14 4SH.
RPS Group Plc web link: <http://www.rpsgroup.com>

**Comment by oceanzus** [comment]
I don't export the DB. No idea what you are on about.

**Comment by FBRTMaka** [comment]
Interesting, well after I imported the csv file of the parameter mappings into postgres I then took the entire DB and dumped the data rebuild script.

Basically, if you do not want to rebuild the database (and I assume you’re not using the manage.py db migrate command) you should just do a sql import on ONLY the insert statements for the parameter table.

Then you can just leave the current DB alone.

Does that help?

—
Matt


On Oct 22, 2015, at 2:38 PM, James Case <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't export the DB. No idea what you are on about.

—
Reply to this email directly or view it on GitHub<https://github.com/asascience-open/ooi-ui-services/pull/419#issuecomment-150316952>.


This e-mail message and any attached file is the property of the sender and is sent in confidence to the addressee only.
Internet communications are not secure and RPS is not responsible for their abuse by third parties, any alteration or corruption in transmission or for any loss or damage caused by a virus or by other means.
 
Any advice contained in this e-mail is for information purposes only.

RPS Group Plc, company number: 208 7786 (England). Registered office: 20 Western Avenue Milton Park Abingdon Oxfordshire OX14 4SH.
RPS Group Plc web link: <http://www.rpsgroup.com>

**Pull request merged**
