### PR TITLE
OpLog search Functionality

### PR DESCRIPTION
**Pull request by c0mster**
Service changes for oplog searching 
@DanielJMaher Please have tested to make sure I didn't miss/break something

Thanks

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@c0mster Oh No!  Test Failed!

**Comment by c0mster** [comment]
@DanielJMaher 
Can you run this through a test again please.

**Comment by birdage** [comment]
@DanielJMaher could you review this one

**Comment by FBRTMaka** [comment]
@c0mster hey cam, I'll pull this down and review now

**Comment by FBRTMaka** [comment]
:+1: nice Cam!

**Comment by birdage** [comment]
this looks to work, tested it out

**Pull request merged**
