### PR TITLE
Mc uframe assets controller

### PR DESCRIPTION
**Pull request by FBRTMaka**
@DanielJMaher 

Conversion for Lat/Lon support, only from uframe for now.  POST and PUT conversion to uframe on the way.

### CODE REVIEW

**Comment by FBRTMaka** [comment]
DON'T PULL YET

**Comment by oceanzus** [comment]
LatLon was only in dev for 3 months and seems to have stalled out.  If we really need to use it please add it to github in case it goes away or we need to maintain it.

**Comment by FBRTMaka** [comment]
You see stalled out, I see matured lol.

Not a bad idea tho, probably all packages we use that aren’t in github should be there also.  (I know there aren’t many)

**Comment by oceanzus** [comment]
Is this ready to merge?

**Comment by DanielJMaher** [comment]
@FBRTMaka Did you add it to github to make sure we dont lose it?

**Comment by FBRTMaka** [comment]
PULL!

**Pull request merged**
