### PR TITLE
need to keep the whoosh index in here

### PR DESCRIPTION
**Pull request by FBRTMaka**
@oceanzus plz don't remove this, it'll break services.

### CODE REVIEW

**Comment by lukecampbell** [comment]
I wouldn't recommend committing binary files. What should be committed is the procedure to generate or fetch them.

**Comment by FBRTMaka** [comment]
I'll get it in the deploy later so it builds the catalog after the db is loaded.

**Comment by lukecampbell** [comment]
well, how did you make the whoosh index?

**Comment by FBRTMaka** [comment]
right now you need to run a shell command of: rebuild_index(model)

**Pull request closed without merging**
