### PR TITLE
Update UI services to use new annotation service

### PR DESCRIPTION
**Pull request by petercable**

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@petercable Thank you for the PR.  I will test this out tomorrow when I'm back in the office.  If all is good we will merge and push to the test server.  Same goes for the UI PR.

**Comment by oceanzus** [comment]
@DanielJMaher Did you test this yet?  I would like to get it merged before yours if possible.

**Comment by DanielJMaher** [comment]
@oceanzus Tested and found an issue .  Made PRs in to Petes UI and Services Branches.  Once they are in we are good to go

**Comment by petercable** [comment]
With Dan's fix I am able to POST new annotations but updating annotations is failing.

**Comment by petercable** [comment]
I am now able to POST new annotations and PUT updates to existing annotations.

**Comment by DanielJMaher** [comment]
@oceanzus Let's get my PR in too and then get it up on uframe.ooi?

**Pull request merged**
