### PR TITLE
Mc cors fix

### PR DESCRIPTION
**Pull request by FBRTMaka**
@DanielJMaher , @birdage , @brian-smith723 , @benjwadams , @dlangston 

Here is a possible fix to having the python UI proxy to the services.  Dan and I tested out a first pass and it was promising.  Would like to also try POST/PUT/DELETE.

@DanielJMaher , this will save a lot of time and headache of putting in a new proxy route for each of the services endpoint.  Is backwards compatible.

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@FBRTMaka Does this have any impact on any other part of the system?

**Comment by FBRTMaka** [comment]
What do you mean? Other than being on the app creation?

Thanks,
Matthew Campbell | ASA Science
Developer
T: +1 401 604 2283<tel:+1%20401%20604%202283>
F: +1 978 284 7808<tel:+1%20978%20284%207808>

On Mar 23, 2015, at 3:13 PM, Dan Maher <notifications@github.com<mailto:notifications@github.com>> wrote:


@FBRTMaka<https://github.com/FBRTMaka> Does this have any impact on any other part of the system?

**Comment by FBRTMaka** [comment]
@DanielJMaher  good to go?

**Comment by DanielJMaher** [comment]
@FBRTMaka I jsut wanted to make sure there are no trickle down/ ripple effects.   These changes are isolated, right?

**Comment by FBRTMaka** [comment]
One of the beauties of modules/blueprints is that it doesn't (and shouldn't) need to touch internal code to be effective.

That said, after doing many integration tests I've learned the more time being used during development the better.  At least 2 weeks of usage is minimum.  So the sooner the better.

**Pull request merged**
