### PR TITLE
moved uframe routes to uframe blueprints, as well as helper methods.

### PR DESCRIPTION
**Pull request by FBRTMaka**
Effort to organize, note the uframe prefix!

so, your proxy route would need to be updated from : ‘/get_data’ to ‘/uframe/get_data’

### CODE REVIEW

**Comment by FBRTMaka** [comment]
@birdage , @lukecampbell , all the routes should be working just as before.  I’ve moved the uframe specific routes and helper methods to the uframe blueprint.

**Comment by birdage** [comment]
@FBRTMaka what request would i use now to get at the data?

**Comment by FBRTMaka** [comment]
If you’re using the proxy, and your route was (resolved) to http://localhost:4000/get_data, this would change to (resolved) http://localhost:4000/uframe/get_data.  Now, once this is done, the proxy will have what ever route you want.  I’m assuming right now, it’s (resolved) http://localhost:5000/api/get_data.

Makes sense?

**Comment by birdage** [comment]
@FBRTMaka yeah cheers!

**Comment by birdage** [comment]
@FBRTMaka ill wait for the travis then merge

**Comment by FBRTMaka** [comment]
roger dodger!

**Comment by birdage** [comment]
@FBRTMaka worked first time :+1:

**Pull request merged**
