### PR TITLE
initial commit for glider tracks

### PR DESCRIPTION
**Pull request by birdage**
DO NOT MERGE

### CODE REVIEW

**Comment by FBRTMaka** [comment]
@birdage , hey bud, got a failed test

**Comment by birdage** [comment]
@FBRTMaka love auto tests!

**Comment by birdage** [comment]
@FBRTMaka passing

**Comment by FBRTMaka** [comment]
@birdage sounds good, I'll pull this down and check it over, then I'll update the caching and send it back your way for your review.

**Comment by birdage** [comment]
@FBRTMaka closed in favor of #398

**Pull request closed without merging**
