### PR TITLE
Resolves triggered A&A using updated TOC stream name changes.

### PR DESCRIPTION
**Pull request by oceanzus**

### CODE REVIEW

**Comment by oceanzus** [comment]
@DanielJMaher @FBRTMaka Please review.

**Comment by oceanzus** [comment]
Note that this PR will require a database build.

**Comment by DanielJMaher** [comment]
@birdage @FBRTMaka 

PLEASE REVIEW ASAP

**Comment by birdage** [comment]
@DanielJMaher looks good to me, @FBRTMaka what do you think?

**Comment by FBRTMaka** [comment]
@oceanzus looks good Jim! :+1:

**Pull request merged**
