### PR TITLE
Mc text search

### PR DESCRIPTION
**Pull request by FBRTMaka**
@lukecampbell First step done: text search for model items. Next step, create a route!

### CODE REVIEW

**Comment by FBRTMaka** [comment]
Good to go?  Going once, going twice...

**Comment by oceanzus** [comment]
Should whoosh_index be added to .gitignore?

**Comment by FBRTMaka** [comment]
Not this initial one, otherwise everyone would have to go into shell and rebuild the index...which is a PITA.  Once I get the rebuild_index into the deployment then we should.

**Comment by FBRTMaka** [comment]
Gone!

**Pull request merged**
