### PR TITLE
Cache Fix for Asset/Event listing

### PR DESCRIPTION
**Pull request by FBRTMaka**
@DanielJMaher , @oceanzus 

I know there is a code freeze, and this isn't critical but I just wanted to put it here so it didn't get lost.

This will GREATLY improve the performance of load times.

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@oceanzus @FBRTMaka Do we understand the full implications of merging this?  Is there a possibility it messes with ANYTHING else?

**Comment by FBRTMaka** [comment]
This makes the caching work correctly.  If you want the asset list and event list cached then this is it.  Otherwise I an log a bug.

**Comment by FBRTMaka** [comment]
Like I said though, not critical.  If you don't need it then maybe just wait till next week.

**Comment by oceanzus** [comment]
I'm going to pull the trigger on this one since we need some speed improvements.

**Pull request merged**
