### PR TITLE
Mc text search

### PR DESCRIPTION
**Pull request by FBRTMaka**
@lukecampbell @DanielJMaher 

Text search API needed to support the construction of the ui backbone searching.  This also implements the catalog rebuild when the services are deployed.

### CODE REVIEW

**Comment by FBRTMaka** [comment]
good to go?

**Comment by DanielJMaher** [comment]
No.  This is going to wait until we have time to dedicate to understanding it's potential impacts.  Without Jim, Luke, Andy, or myself able to dedicate time to this review, it will probably sit until Thursday.  Will this impede your work for the week?

**Comment by FBRTMaka** [comment]
Sounds good, nah it's cool.

**Comment by DanielJMaher** [comment]
@FBRTMaka Why is this closed now?

**Comment by FBRTMaka** [comment]
We're waiting till Thursday!

**Comment by FBRTMaka** [comment]
If you WANT to be distracted, I can add it back.  But I'd rather not have a PR open cause confusion for no reason.

**Pull request closed without merging**
