### PR TITLE
Changes "Regional Scale" to "Cabled Array" in the array table.

### PR DESCRIPTION
**Pull request by oceanzus**

### CODE REVIEW

**Comment by birdage** [comment]
:+1:

**Comment by DanielJMaher** [comment]
@birdage Travis hadn't passed yet.. had it?

**Comment by oceanzus** [comment]
PLEASE REVERT THIS.  THE TESTS NEED TO BE CHANGED ME THINKS!

**Comment by oceanzus** [comment]
It looks like they will run, but using the RSN verbage.

**Comment by DanielJMaher** [comment]
@oceanzus @birdage it failed AGAIN

**Pull request merged**
