### PR TITLE
Updates to support A&A using uframe's qpid messaging.

### PR DESCRIPTION
**Pull request by oceanzus**
DO NOT MERGE YET

### CODE REVIEW

**Comment by birdage** [comment]
@oceanzus how we looking?

**Comment by oceanzus** [comment]
Not ready yet.  Many changes afoot.

**Comment by oceanzus** [comment]
@birdage Please review and merge if comfortable.

**Comment by DanielJMaher** [comment]
@FBRTMaka Review as well?

**Comment by birdage** [comment]
@FBRTMaka im ready to hit merge if you think its ok, give me the thumbs up!

**Comment by oceanzus** [comment]
Please merge this as the ooi-ui portion is merged. Thank you guys for reviewing!

**Pull request merged**
