### PR TITLE
remove 2 day block

### PR DESCRIPTION
**Pull request by birdage**

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@birdage Do we have/need a time check for end time being after start time

**Comment by birdage** [comment]
@DanielJMaher doesn't uframe handle this? also we also handle it in the ui? do you think we need another check, maybe a swap?

**Comment by DanielJMaher** [comment]
Actually this doesn't even validate anyhting... bad name for a function.  We should really remove the call of this function and delete the entire thing.. is that going to be difficult?

**Comment by birdage** [comment]
@DanielJMaher i can do it but i dont know what the down stream effects would be, yes?

**Pull request merged**
