### PR TITLE
Added this line to force the redmine api to work.

### PR DESCRIPTION
**Pull request by DanielJMaher**

### CODE REVIEW

**Comment by FBRTMaka** [comment]
@DanielJMaher this ready to go?

**Comment by DanielJMaher** [comment]
@FBRTMaka No. This was mostly a hack for Edna to do her work.  We need to properly evaluate what is needed.  This will work in a pinch, but isn't done right.

**Comment by FBRTMaka** [comment]
k

**Comment by birdage** [comment]
@DanielJMaher are we keeping this open?

**Comment by DanielJMaher** [comment]
This is going to be kept open so we can address the alrger under lying issue

**Comment by birdage** [comment]
@DanielJMaher can we close this now?

**Comment by birdage** [comment]
@DanielJMaher status on this?

**Comment by Bobfrat** [comment]
This has been fixed!

**Pull request closed without merging**
