### PR TITLE
Adds display name functionality for TOC.

### PR DESCRIPTION
**Pull request by oceanzus**
Adds platformnames and instrumentnames tables and associated SQLAlchemy models.
Updates database scripts.

### CODE REVIEW

**Comment by FBRTMaka** [comment]
why is the db hard coded?

**Comment by oceanzus** [comment]
hard-coded because the session doesn't seem to persist at that level.  I welcome suggestions as to how I can accomplish a stored procedure call without the session.  Please suggest a better alternative to toc.py

**Comment by FBRTMaka** [comment]
could also have an sql injection there too with that execute...maybe :p

**Comment by FBRTMaka** [comment]
ref spc, I think I saw a way to do that...let me look back

**Pull request merged**
