### PR TITLE
Mc new pages

### PR DESCRIPTION
**Pull request by maka-io**
@DanielJMaher , @oceanzus 

update for getting platforms to the home page

### CODE REVIEW

**Comment by oceanzus** [comment]
@maka-io This conflicts with Edna's work.  Please do not merge this.

**Comment by DanielJMaher** [comment]
@oceanzus Good Catch.  How do we get them inline?

**Comment by oceanzus** [comment]
@DanielJMaher @maka-io There will be a PR incoming this afternoon, hopefully before 3pm.  We can then figure out how to align things.

**Comment by maka-io** [comment]
@oceanzus @DanielJMaher updated to merge in with master from this morning's merge

**Pull request merged**
