### PR TITLE
routes and model for instrument change

### PR DESCRIPTION
**Pull request by ssontag55**

### CODE REVIEW

**Comment by FBRTMaka** [comment]
What's up with the DELETE in the POST/PUT?  This will be hard to assign permissions to, and I could be wrong but it's not very "Restful".  Right?

**Comment by ssontag55** [comment]
I hear you. You could still add the permissions in that call but I could rip it apart into more restfulness.

**Comment by FBRTMaka** [comment]
all set bud, Luke took a stab at it

Thanks,
Matthew Campbell | Agfa HealthCare - Technical Project Manager
T: +1 401 604 2283
F: +1 978 284 7808

On Feb 7, 2015, at 5:41 PM, stephen sontag <notifications@github.com<mailto:notifications@github.com>> wrote:


I hear you. You could still add the permissions in that call but I could rip it apart into more restfulness.

**Comment by lukecampbell** [comment]
Я съем твою душу, то пончики.

**Pull request merged**
